# Generated by Django 4.2 on 2023-05-05 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_poster_alter_film_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='ImageField',
            new_name='imagefield',
        ),
        migrations.AddField(
            model_name='poster',
            name='film_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='films.film'),
            preserve_default=False,
        ),
    ]
