# Generated by Django 4.2 on 2023-05-06 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0006_rename_imagefield_poster_imagefield_poster_film_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.date(2023, 5, 6)),
        ),
        migrations.CreateModel(
            name='RatingCommentnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_comment_for_film', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_comment_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
