# Generated by Django 4.2.1 on 2023-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='birth_date',
            field=models.DateField(default='1800-01-01', verbose_name='Birth date:'),
        ),
    ]
