# Generated by Django 4.2 on 2023-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_category_image_alter_todo_date_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
    ]
