# Generated by Django 4.2.1 on 2023-05-08 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ManyToManyField(related_name='reg_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
