# Generated by Django 4.2.1 on 2023-05-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_book_cnt_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
